#!/bin/bash

# Clear all credential helpers
sudo git config --system --unset-all 'credential.helper'
git config --global --unset-all 'credential.helper'
git config --global --unset-all 'credential.https://github.com.helper'
git config --global --add 'credential.https://github.com.helper' '!gh auth git-credential'

# Clear GITHUB_TOKEN, so we can re-auth
export GITHUB_TOKEN=

# Login to the GH CLI
gh auth login

export GITHUB_TOKEN=

echo "Successfully added 'gh auth git-credential' as your git credential helper."
