#!/bin/bash

sudo git config --system --unset-all 'credential.helper'
git config --global --unset-all 'credential.helper'
git config --global --unset-all 'credential.https://github.com.helper'
git config --global --add 'credential.https://github.com.helper' '!gh auth git-credential'

# First clear the GITHUB_TOKEN so gh auth login works
export GITHUB_TOKEN=

# Second login to gh cli
gh auth login

echo "Successfully added 'gh auth git-credential' as your git credential helper."
