#!/bin/bash

# Clear all credential helpers
git config --global --unset-all 'credential.https://github.com.helper'
git config --global --add 'credential.https://github.com.helper' '!gh auth git-credential'

# Clear GITHUB_TOKEN, so we can re-auth
export GITHUB_TOKEN=

# Login to the GH CLI
gh auth login

echo "Successfully added 'gh auth git-credential' as your git credential helper."
